// .github/scripts/post_pr_comment.mjs
import fs from "fs";

const DIFF_FILE = "/tmp/diff_output.md";
const MARKER = "📊 Excel Diff Report";

export default async ({ github, context }) => {
  // Read diff if it exists, otherwise treat as empty
  let diff = "";
  try {
    diff = fs.readFileSync(DIFF_FILE, "utf8").trim();
  } catch {
    // file doesn't exist — no diff generated
  }

  const { data: comments } = await github.rest.issues.listComments({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: context.issue.number,
  });

  const botComment = comments.find((c) => c.body.includes(MARKER));

  // No changes — delete existing comment if present
  if (!diff) {
    if (botComment) {
      await github.rest.issues.deleteComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        comment_id: botComment.id,
      });
      console.log("No changes — deleted existing comment");
    } else {
      console.log("No changes — nothing to do");
    }
    return;
  }

  // Changes exist — create or update comment
  const body = `# ${MARKER}\n\n${diff}\n\n---\n_Auto-generated by excel-diff action_`;

  if (botComment) {
    await github.rest.issues.updateComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      comment_id: botComment.id,
      body,
    });
    console.log(`Updated existing comment #${botComment.id}`);
  } else {
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: context.issue.number,
      body,
    });
    console.log("Created new comment");
  }
};
