// .github/scripts/post_pr_comment.js
import fs from "fs";

const DIFF_FILE = "/tmp/diff_output.md";
const MARKER = "📊 Excel Diff Report";

export default async ({ github, context }) => {
  const diff = fs.readFileSync(DIFF_FILE, "utf8");

  const body = `# ${MARKER}\n\n${diff}\n\n---\n_Auto-generated by excel-diff action_`;

  const { data: comments } = await github.rest.issues.listComments({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: context.issue.number,
  });

  const botComment = comments.find((c) => c.body.includes(MARKER));

  if (botComment) {
    await github.rest.issues.updateComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      comment_id: botComment.id,
      body,
    });
  } else {
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: context.issue.number,
      body,
    });
  }
};
