const fs = require("fs");
const diff = fs.readFileSync("/tmp/diff_output.md", "utf8");

const body = `# 📊 Excel Diff Report\n\n${diff}\n\n---\n_Auto-generated by excel-diff action_`;

const { data: comments } = await github.rest.issues.listComments({
  owner: context.repo.owner,
  repo: context.repo.repo,
  issue_number: context.issue.number,
});

const botComment = comments.find((c) =>
  c.body.includes("📊 Excel Diff Report"),
);

if (botComment) {
  await github.rest.issues.updateComment({
    owner: context.repo.owner,
    repo: context.repo.repo,
    comment_id: botComment.id,
    body,
  });
} else {
  await github.rest.issues.createComment({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: context.issue.number,
    body,
  });
}
